name: Call Endpoint on Push to Main

on:
  push:
    branches:
      - main

jobs:
  call_endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Call endpoint
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "ref": "${{ github.ref }}", 
            "repo": "${{ github.repository }}", 
            "commit": "${{ github.event.after }}"
            }' \
           ${{ secrets.ENDPOINT }}
